### ISSUE TITLE
Runtime crash - BUILD_LIBRARY_FOR_DISTRIBUTION

### ISSUE THREAD

**Issue by jeff-odopass** [ScreebApp/sdk-ios-public#1]
Salut,

En implémentant le SDK IOS dans mon app Flutter je suis tombé sur un crash au runtime, dès le tout premier appel à Screeb:
```
[+2179 ms] (lldb) dyld[1190]: Symbol not found: _$s10Kingfisher0A15OptionsInfoItemO9processoryAcA14ImageProcessor_pcACmFWC
[   +2 ms]   Referenced from: /private/var/containers/Bundle/Application/CCBE8247-EB5E-4EA7-94E7-934231B64DA2/Odopass.app/Frameworks/Screeb.framework/Screeb
[        ]   Expected in: /private/var/containers/Bundle/Application/CCBE8247-EB5E-4EA7-94E7-934231B64DA2/Odopass.app/Frameworks/Kingfisher.framework/Kingfisher
[  +12 ms] Process 1190 stopped
[   +2 ms] * thread #1, stop reason = signal SIGABRT
[        ]     frame #0: 0x0000000107f38198 dyld`__abort_with_payload + 8
[        ] dyld`__abort_with_payload:
[        ] ->  0x107f38198 <+8>:  b.lo   0x107f381b8               ; <+40>
[        ]     0x107f3819c <+12>: pacibsp 
[        ]     0x107f381a0 <+16>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x107f381a4 <+20>: mov    x29, sp
```
C'est donc la lib tierce de cache d'image Kingfisher qui n'est pas trouvée.

Après quelque recherches il semble que ce soit dû à la propriété BUILD_LIBRARY_FOR_DISTRIBUTION, qui a été set à `true` lors du build du SDK Screeb, et qui n'est pas inférée par Cocoapods.
Lors du build côté client cette valeur n'est pas `true`, ce qui peut créer des runtime failure comme c'est le cas ici.

Workaround côté client:
Podfile
```
post_install do |installer|
  ...
  installer.pods_project.targets.each do |target|
    ...

    target.build_configurations.each do |config|
      ...
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
```
Thread intéressant: https://github.com/CocoaPods/CocoaPods/issues/9232

Je ne suis pas du tout un expert IOS/Swift, et je ne sais donc pas si c'est normal que nous devions faire ce fix de notre côté, ça n'a jamais été le cas jusqu’à présent. Je ne sais aussi pas si cela peut avoir des impacts, et si le build de l'IPA de production sera fonctionnel non-plus.

Ce n'est pas forcément bloquant de mon côté car je vais plutôt attendre l'intégration officielle du SDK via un package Flutter, je voulais surtout vous prévenir !

**Comment by clement-screeb** [comment]
Salut Jeff,

Merci pour ce retour. 
Effectivement ce paramètre fait partie de l'intégration du sdk comme tu peux le voir dans le Podfile de l'app de démo.
Il s'agit simplement d'un oubli dans la doc que je corrige tout de suite.
Pas d'inquiétude pour l'intégrer dans une app a priori, c'est assez courant pour des sdk "closed-source" (ex : https://github.com/iadvize/iadvize-ios-sdk)
